all:
	g++ -O2 -std=c++17 tp3.cpp q1q3homogene.cpp q6q8temperature.cpp q10q11maxtries.cpp -o tp3

run: all
	./tp3

clean:
	rm -f tp3 q1q3homogene q6q8temperature q10q11maxtries tp3_old.cpp *.res *.png *.txt