all:
	g++ -O2 -std=c++17 tp3.cpp q1_q3_homogene.cpp q6_q8_temperature.cpp q10_q11_maxtries.cpp -o tp3

run: all
	./tp3

clean:
	rm -f tp3 q1_q3_homogene q6_q8_temperature q10_q11_maxtries tp3_old.cpp *.res *.png *.txt